version: '3.8'

services:
  react-native-app:
    build: .
    ports:
      - "8081:8081" # Expose Metro Bundler port
    volumes:
      - .:/app # Mount current directory to /app in the container
      - /app/node_modules
    command: ["npx", "react-native", "start", "--host", "0.0.0.0"]
